import React, { createContext, useContext, useState } from 'react';

export type Language = 
  | 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'zh' | 'ja' | 'ko' 
  | 'ar' | 'hi' | 'bn' | 'pa' | 'te' | 'mr' | 'ta' | 'ur' | 'gu' | 'kn'
  | 'ml' | 'th' | 'vi' | 'id' | 'tr' | 'pl' | 'nl' | 'sv' | 'no' | 'da';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Aqua Harvest',
    tagline: 'Capture. Recharge. Sustain.',
    selectLanguage: 'Select Your Language',
    continue: 'Continue',
    name: 'Name',
    phone: 'Phone Number',
    district: 'District',
    occupation: 'Occupation',
    floodRisk: 'Flood risk in your area?',
    solarPanels: 'Do you have solar panels?',
    tankType: 'Tank Type',
    plastic: 'Plastic',
    cement: 'Cement',
    frontPlastic: 'Front Plastic Tank',
    rooftopPlastic: 'Rooftop Plastic Tank',
    frontCement: 'Front Cement Tank',
    rooftopCement: 'Rooftop Cement Tank',
    undergroundCement: 'Underground Cement Tank',
    familySize: 'Family Size',
    storageDays: 'Storage Days',
    recommendedCapacity: 'Recommended Tank Capacity',
    liters: 'Liters',
    yes: 'Yes',
    no: 'No',
    dashboard: 'Dashboard',
    analytics: 'Analytics',
    mainTank: 'Main Tank',
    rainwaterTank: 'Rainwater Tank',
    transferToPit: 'Transfer to Recharge Pit',
    transferToMain: 'Transfer to Main Tank',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainfall: 'Rainfall Chance',
    phLevel: 'pH Level',
    waterQuality: 'Water Quality',
    good: 'Good',
    moderate: 'Moderate',
    poor: 'Poor',
    refillTime: 'Estimated Refill Time',
    hours: 'hours',
    totalCollected: 'Total Rainwater Collected',
    totalReused: 'Total Water Reused',
    waterSaved: 'Water Saved This Month',
    rechargePit: 'Recharge Pit Contribution',
    tankEfficiency: 'Tank Efficiency',
    dailyRainfall: 'Daily Rainfall Tracker',
    tankHistory: 'Tank Level History',
  },
  es: {
    appName: 'Aqua Harvest',
    tagline: 'Capturar. Recargar. Sostener.',
    selectLanguage: 'Seleccione su idioma',
    continue: 'Continuar',
    name: 'Nombre',
    phone: 'Número de teléfono',
    district: 'Distrito',
    occupation: 'Ocupación',
    floodRisk: '¿Riesgo de inundación en su área?',
    solarPanels: '¿Tiene paneles solares?',
    tankType: 'Tipo de tanque',
    plastic: 'Plástico',
    cement: 'Cemento',
    frontPlastic: 'Tanque de plástico frontal',
    rooftopPlastic: 'Tanque de plástico en azotea',
    frontCement: 'Tanque de cemento frontal',
    rooftopCement: 'Tanque de cemento en azotea',
    undergroundCement: 'Tanque de cemento subterráneo',
    familySize: 'Tamaño de la familia',
    storageDays: 'Días de almacenamiento',
    recommendedCapacity: 'Capacidad recomendada del tanque',
    liters: 'Litros',
    yes: 'Sí',
    no: 'No',
    dashboard: 'Panel de control',
    analytics: 'Analítica',
    mainTank: 'Tanque principal',
    rainwaterTank: 'Tanque de agua de lluvia',
    transferToPit: 'Transferir a pozo de recarga',
    transferToMain: 'Transferir al tanque principal',
    temperature: 'Temperatura',
    humidity: 'Humedad',
    rainfall: 'Probabilidad de lluvia',
    phLevel: 'Nivel de pH',
    waterQuality: 'Calidad del agua',
    good: 'Bueno',
    moderate: 'Moderado',
    poor: 'Pobre',
    refillTime: 'Tiempo estimado de recarga',
    hours: 'horas',
    totalCollected: 'Total de agua de lluvia recolectada',
    totalReused: 'Total de agua reutilizada',
    waterSaved: 'Agua ahorrada este mes',
    rechargePit: 'Contribución del pozo de recarga',
    tankEfficiency: 'Eficiencia del tanque',
    dailyRainfall: 'Rastreador de lluvia diaria',
    tankHistory: 'Historial del nivel del tanque',
  },
  fr: {
    appName: 'Aqua Harvest',
    tagline: 'Capturer. Recharger. Maintenir.',
    selectLanguage: 'Sélectionnez votre langue',
    continue: 'Continuer',
    name: 'Nom',
    phone: 'Numéro de téléphone',
    district: 'District',
    occupation: 'Profession',
    floodRisk: 'Risque d\'inondation dans votre région?',
    solarPanels: 'Avez-vous des panneaux solaires?',
    tankType: 'Type de réservoir',
    plastic: 'Plastique',
    cement: 'Ciment',
    frontPlastic: 'Réservoir en plastique avant',
    rooftopPlastic: 'Réservoir en plastique sur le toit',
    frontCement: 'Réservoir en ciment avant',
    rooftopCement: 'Réservoir en ciment sur le toit',
    undergroundCement: 'Réservoir en ciment souterrain',
    familySize: 'Taille de la famille',
    storageDays: 'Jours de stockage',
    recommendedCapacity: 'Capacité recommandée du réservoir',
    liters: 'Litres',
    yes: 'Oui',
    no: 'Non',
    dashboard: 'Tableau de bord',
    analytics: 'Analytique',
    mainTank: 'Réservoir principal',
    rainwaterTank: 'Réservoir d\'eau de pluie',
    transferToPit: 'Transférer vers le puits de recharge',
    transferToMain: 'Transférer vers le réservoir principal',
    temperature: 'Température',
    humidity: 'Humidité',
    rainfall: 'Probabilité de pluie',
    phLevel: 'Niveau de pH',
    waterQuality: 'Qualité de l\'eau',
    good: 'Bon',
    moderate: 'Modéré',
    poor: 'Mauvais',
    refillTime: 'Temps de remplissage estimé',
    hours: 'heures',
    totalCollected: 'Total d\'eau de pluie collectée',
    totalReused: 'Total d\'eau réutilisée',
    waterSaved: 'Eau économisée ce mois-ci',
    rechargePit: 'Contribution du puits de recharge',
    tankEfficiency: 'Efficacité du réservoir',
    dailyRainfall: 'Suivi des précipitations quotidiennes',
    tankHistory: 'Historique du niveau du réservoir',
  },
  hi: {
    appName: 'एक्वा हार्वेस्ट',
    tagline: 'कैप्चर करें। रिचार्ज करें। बनाए रखें।',
    selectLanguage: 'अपनी भाषा चुनें',
    continue: 'जारी रखें',
    name: 'नाम',
    phone: 'फोन नंबर',
    district: 'जिला',
    occupation: 'व्यवसाय',
    floodRisk: 'आपके क्षेत्र में बाढ़ का खतरा?',
    solarPanels: 'क्या आपके पास सोलर पैनल हैं?',
    tankType: 'टैंक का प्रकार',
    plastic: 'प्लास्टिक',
    cement: 'सीमेंट',
    frontPlastic: 'सामने प्लास्टिक टैंक',
    rooftopPlastic: 'छत पर प्लास्टिक टैंक',
    frontCement: 'सामने सीमेंट टैंक',
    rooftopCement: 'छत पर सीमेंट टैंक',
    undergroundCement: 'भूमिगत सीमेंट टैंक',
    familySize: 'परिवार का आकार',
    storageDays: 'भंडारण दिन',
    recommendedCapacity: 'अनुशंसित टैंक क्षमता',
    liters: 'लीटर',
    yes: 'हाँ',
    no: 'नहीं',
    dashboard: 'डैशबोर्ड',
    analytics: 'विश्लेषण',
    mainTank: 'मुख्य टैंक',
    rainwaterTank: 'वर्षा जल टैंक',
    transferToPit: 'रिचार्ज पिट में स्थानांतरित करें',
    transferToMain: 'मुख्य टैंक में स्थानांतरित करें',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainfall: 'वर्षा की संभावना',
    phLevel: 'पीएच स्तर',
    waterQuality: 'जल गुणवत्ता',
    good: 'अच्छा',
    moderate: 'मध्यम',
    poor: 'खराब',
    refillTime: 'अनुमानित भरने का समय',
    hours: 'घंटे',
    totalCollected: 'कुल वर्षा जल संग्रहित',
    totalReused: 'कुल पानी पुन: उपयोग किया गया',
    waterSaved: 'इस महीने बचाया गया पानी',
    rechargePit: 'रिचार्ज पिट योगदान',
    tankEfficiency: 'टैंक दक्षता',
    dailyRainfall: 'दैनिक वर्षा ट्रैकर',
    tankHistory: 'टैंक स्तर इतिहास',
  },
  zh: {
    appName: '水收获',
    tagline: '捕获。充电。维持。',
    selectLanguage: '选择您的语言',
    continue: '继续',
    name: '姓名',
    phone: '电话号码',
    district: '地区',
    occupation: '职业',
    floodRisk: '您所在地区有洪水风险吗？',
    solarPanels: '您有太阳能电池板吗？',
    tankType: '水箱类型',
    plastic: '塑料',
    cement: '水泥',
    frontPlastic: '前置塑料水箱',
    rooftopPlastic: '屋顶塑料水箱',
    frontCement: '前置水泥水箱',
    rooftopCement: '屋顶水泥水箱',
    undergroundCement: '地下水泥水箱',
    familySize: '家庭规模',
    storageDays: '存储天数',
    recommendedCapacity: '推荐水箱容量',
    liters: '升',
    yes: '是',
    no: '否',
    dashboard: '仪表板',
    analytics: '分析',
    mainTank: '主水箱',
    rainwaterTank: '雨水箱',
    transferToPit: '转移到补给坑',
    transferToMain: '转移到主水箱',
    temperature: '温度',
    humidity: '湿度',
    rainfall: '降雨概率',
    phLevel: 'pH值',
    waterQuality: '水质',
    good: '良好',
    moderate: '中等',
    poor: '差',
    refillTime: '预计补充时间',
    hours: '小时',
    totalCollected: '收集的总雨水',
    totalReused: '重复使用的总水量',
    waterSaved: '本月节约的水',
    rechargePit: '补给坑贡献',
    tankEfficiency: '水箱效率',
    dailyRainfall: '每日降雨跟踪器',
    tankHistory: '水箱水位历史',
  },
  ar: {
    appName: 'حصاد المياه',
    tagline: 'التقط. أعد الشحن. استدام.',
    selectLanguage: 'اختر لغتك',
    continue: 'استمر',
    name: 'الاسم',
    phone: 'رقم الهاتف',
    district: 'المنطقة',
    occupation: 'المهنة',
    floodRisk: 'خطر الفيضانات في منطقتك؟',
    solarPanels: 'هل لديك ألواح شمسية؟',
    tankType: 'نوع الخزان',
    plastic: 'بلاستيك',
    cement: 'أسمنت',
    frontPlastic: 'خزان بلاستيكي أمامي',
    rooftopPlastic: 'خزان بلاستيكي على السطح',
    frontCement: 'خزان أسمنتي أمامي',
    rooftopCement: 'خزان أسمنتي على السطح',
    undergroundCement: 'خزان أسمنتي تحت الأرض',
    familySize: 'حجم الأسرة',
    storageDays: 'أيام التخزين',
    recommendedCapacity: 'سعة الخزان الموصى بها',
    liters: 'لتر',
    yes: 'نعم',
    no: 'لا',
    dashboard: 'لوحة التحكم',
    analytics: 'التحليلات',
    mainTank: 'الخزان الرئيسي',
    rainwaterTank: 'خزان مياه الأمطار',
    transferToPit: 'نقل إلى حفرة إعادة الشحن',
    transferToMain: 'نقل إلى الخزان الرئيسي',
    temperature: 'درجة الحرارة',
    humidity: 'الرطوبة',
    rainfall: 'فرصة هطول الأمطار',
    phLevel: 'مستوى الأس الهيدروجيني',
    waterQuality: 'جودة المياه',
    good: 'جيد',
    moderate: 'معتدل',
    poor: 'ضعيف',
    refillTime: 'وقت إعادة الملء المقدر',
    hours: 'ساعات',
    totalCollected: 'إجمالي مياه الأمطار المجمعة',
    totalReused: 'إجمالي المياه المعاد استخدامها',
    waterSaved: 'المياه الموفرة هذا الشهر',
    rechargePit: 'مساهمة حفرة إعادة الشحن',
    tankEfficiency: 'كفاءة الخزان',
    dailyRainfall: 'متتبع هطول الأمطار اليومي',
    tankHistory: 'تاريخ مستوى الخزان',
  },
  // Adding more languages with key translations
  de: { appName: 'Aqua Harvest', tagline: 'Erfassen. Aufladen. Erhalten.', selectLanguage: 'Wählen Sie Ihre Sprache', continue: 'Weiter', name: 'Name', phone: 'Telefonnummer', district: 'Bezirk', occupation: 'Beruf', yes: 'Ja', no: 'Nein', dashboard: 'Dashboard', analytics: 'Analytik' },
  pt: { appName: 'Aqua Harvest', tagline: 'Capturar. Recarregar. Sustentar.', selectLanguage: 'Selecione seu idioma', continue: 'Continuar', name: 'Nome', phone: 'Número de telefone', district: 'Distrito', occupation: 'Ocupação', yes: 'Sim', no: 'Não', dashboard: 'Painel', analytics: 'Análise' },
  ru: { appName: 'Aqua Harvest', tagline: 'Захватывать. Перезаряжать. Поддерживать.', selectLanguage: 'Выберите свой язык', continue: 'Продолжить', name: 'Имя', phone: 'Номер телефона', district: 'Район', occupation: 'Занятие', yes: 'Да', no: 'Нет', dashboard: 'Панель управления', analytics: 'Аналитика' },
  ja: { appName: 'アクアハーベスト', tagline: 'キャプチャ。リチャージ。維持。', selectLanguage: '言語を選択', continue: '続ける', name: '名前', phone: '電話番号', district: '地区', occupation: '職業', yes: 'はい', no: 'いいえ', dashboard: 'ダッシュボード', analytics: '分析' },
  ko: { appName: '아쿠아 하베스트', tagline: '캡처. 충전. 유지.', selectLanguage: '언어 선택', continue: '계속', name: '이름', phone: '전화번호', district: '지역', occupation: '직업', yes: '예', no: '아니오', dashboard: '대시보드', analytics: '분석' },
  bn: { appName: 'অ্যাকুয়া হার্ভেস্ট', tagline: 'ক্যাপচার। রিচার্জ। বজায় রাখুন।', selectLanguage: 'আপনার ভাষা নির্বাচন করুন', continue: 'চালিয়ে যান', name: 'নাম', phone: 'ফোন নম্বর', district: 'জেলা', occupation: 'পেশা', yes: 'হ্যাঁ', no: 'না', dashboard: 'ড্যাশবোর্ড', analytics: 'বিশ্লেষণ' },
  ta: { appName: 'அக்வா ஹார்வெஸ்ட்', tagline: 'பிடி. ரீசார்ஜ். நிலைநிறுத்து.', selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்', continue: 'தொடரவும்', name: 'பெயர்', phone: 'தொலைபேசி எண்', district: 'மாவட்டம்', occupation: 'தொழில்', yes: 'ஆம்', no: 'இல்லை', dashboard: 'டாஷ்போர்டு', analytics: 'பகுப்பாய்வு' },
  te: { appName: 'అక్వా హార్వెస్ట్', tagline: 'క్యాప్చర్. రీఛార్జ్. సస్టెయిన్.', selectLanguage: 'మీ భాషను ఎంచుకోండి', continue: 'కొనసాగించు', name: 'పేరు', phone: 'ఫోన్ నంబర్', district: 'జిల్లా', occupation: 'వృత్తి', yes: 'అవును', no: 'కాదు', dashboard: 'డ్యాష్‌బోర్డ్', analytics: 'విశ్లేషణ' },
  mr: { appName: 'एक्वा हार्वेस्ट', tagline: 'कॅप्चर करा. रिचार्ज करा. टिकवा.', selectLanguage: 'तुमची भाषा निवडा', continue: 'सुरू ठेवा', name: 'नाव', phone: 'फोन नंबर', district: 'जिल्हा', occupation: 'व्यवसाय', yes: 'होय', no: 'नाही', dashboard: 'डॅशबोर्ड', analytics: 'विश्लेषण' },
  it: { appName: 'Aqua Harvest', tagline: 'Catturare. Ricaricare. Sostenere.', selectLanguage: 'Seleziona la tua lingua', continue: 'Continua', name: 'Nome', phone: 'Numero di telefono', district: 'Distretto', occupation: 'Occupazione', yes: 'Sì', no: 'No', dashboard: 'Cruscotto', analytics: 'Analitica' },
  tr: { appName: 'Aqua Harvest', tagline: 'Yakala. Şarj et. Sürdür.', selectLanguage: 'Dilinizi seçin', continue: 'Devam et', name: 'Ad', phone: 'Telefon numarası', district: 'Bölge', occupation: 'Meslek', yes: 'Evet', no: 'Hayır', dashboard: 'Gösterge paneli', analytics: 'Analitik' },
  vi: { appName: 'Aqua Harvest', tagline: 'Bắt. Nạp lại. Duy trì.', selectLanguage: 'Chọn ngôn ngữ của bạn', continue: 'Tiếp tục', name: 'Tên', phone: 'Số điện thoại', district: 'Quận', occupation: 'Nghề nghiệp', yes: 'Có', no: 'Không', dashboard: 'Bảng điều khiển', analytics: 'Phân tích' },
  th: { appName: 'Aqua Harvest', tagline: 'จับ. ชาร์จ. รักษา.', selectLanguage: 'เลือกภาษาของคุณ', continue: 'ดำเนินการต่อ', name: 'ชื่อ', phone: 'หมายเลขโทรศัพท์', district: 'เขต', occupation: 'อาชีพ', yes: 'ใช่', no: 'ไม่', dashboard: 'แดชบอร์ด', analytics: 'การวิเคราะห์' },
  id: { appName: 'Aqua Harvest', tagline: 'Tangkap. Isi Ulang. Pertahankan.', selectLanguage: 'Pilih bahasa Anda', continue: 'Lanjutkan', name: 'Nama', phone: 'Nomor telepon', district: 'Distrik', occupation: 'Pekerjaan', yes: 'Ya', no: 'Tidak', dashboard: 'Dasbor', analytics: 'Analitik' },
  pl: { appName: 'Aqua Harvest', tagline: 'Przechwytuj. Ładuj. Utrzymuj.', selectLanguage: 'Wybierz swój język', continue: 'Kontynuuj', name: 'Nazwa', phone: 'Numer telefonu', district: 'Dystrykt', occupation: 'Zawód', yes: 'Tak', no: 'Nie', dashboard: 'Pulpit', analytics: 'Analityka' },
  nl: { appName: 'Aqua Harvest', tagline: 'Vangen. Opladen. Behouden.', selectLanguage: 'Selecteer uw taal', continue: 'Doorgaan', name: 'Naam', phone: 'Telefoonnummer', district: 'District', occupation: 'Beroep', yes: 'Ja', no: 'Nee', dashboard: 'Dashboard', analytics: 'Analyse' },
  sv: { appName: 'Aqua Harvest', tagline: 'Fånga. Ladda. Bibehåll.', selectLanguage: 'Välj ditt språk', continue: 'Fortsätt', name: 'Namn', phone: 'Telefonnummer', district: 'Distrikt', occupation: 'Yrke', yes: 'Ja', no: 'Nej', dashboard: 'Instrumentpanel', analytics: 'Analys' },
  pa: { appName: 'ਐਕੁਆ ਹਾਰਵੇਸਟ', tagline: 'ਕੈਪਚਰ। ਰੀਚਾਰਜ। ਕਾਇਮ ਰੱਖੋ।', selectLanguage: 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ', continue: 'ਜਾਰੀ ਰੱਖੋ', name: 'ਨਾਮ', phone: 'ਫੋਨ ਨੰਬਰ', district: 'ਜ਼ਿਲ੍ਹਾ', occupation: 'ਪੇਸ਼ਾ', yes: 'ਹਾਂ', no: 'ਨਹੀਂ', dashboard: 'ਡੈਸ਼ਬੋਰਡ', analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ' },
  ur: { appName: 'ایکوا ہاروسٹ', tagline: 'کیپچر۔ ریچارج۔ برقرار رکھیں۔', selectLanguage: 'اپنی زبان منتخب کریں', continue: 'جاری رکھیں', name: 'نام', phone: 'فون نمبر', district: 'ضلع', occupation: 'پیشہ', yes: 'ہاں', no: 'نہیں', dashboard: 'ڈیش بورڈ', analytics: 'تجزیات' },
  gu: { appName: 'એક્વા હાર્વેસ્ટ', tagline: 'કેપ્ચર. રિચાર્જ. ટકાવી રાખો.', selectLanguage: 'તમારી ભાષા પસંદ કરો', continue: 'ચાલુ રાખો', name: 'નામ', phone: 'ફોન નંબર', district: 'જિલ્લો', occupation: 'વ્યવસાય', yes: 'હા', no: 'ના', dashboard: 'ડેશબોર્ડ', analytics: 'વિશ્લેષણ' },
  kn: { appName: 'ಆಕ್ವಾ ಹಾರ್ವೆಸ್ಟ್', tagline: 'ಸೆರೆಹಿಡಿ. ರೀಚಾರ್ಜ್. ನಿರ್ವಹಿಸಿ.', selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ', continue: 'ಮುಂದುವರಿಸಿ', name: 'ಹೆಸರು', phone: 'ಫೋನ್ ಸಂಖ್ಯೆ', district: 'ಜಿಲ್ಲೆ', occupation: 'ವೃತ್ತಿ', yes: 'ಹೌದು', no: 'ಇಲ್ಲ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', analytics: 'ವಿಶ್ಲೇಷಣೆ' },
  ml: { appName: 'അക്വാ ഹാർവെസ്റ്റ്', tagline: 'പിടിക്കുക. റീചാർജ്. നിലനിർത്തുക.', selectLanguage: 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക', continue: 'തുടരുക', name: 'പേര്', phone: 'ഫോൺ നമ്പർ', district: 'ജില്ല', occupation: 'തൊഴിൽ', yes: 'അതെ', no: 'ഇല്ല', dashboard: 'ഡാഷ്‌ബോർഡ്', analytics: 'വിശകലനം' },
  no: { appName: 'Aqua Harvest', tagline: 'Fang. Lad opp. Oppretthold.', selectLanguage: 'Velg språk', continue: 'Fortsett', name: 'Navn', phone: 'Telefonnummer', district: 'Distrikt', occupation: 'Yrke', yes: 'Ja', no: 'Nei', dashboard: 'Dashbord', analytics: 'Analyse' },
  da: { appName: 'Aqua Harvest', tagline: 'Fang. Genoplad. Oprethold.', selectLanguage: 'Vælg dit sprog', continue: 'Fortsæt', name: 'Navn', phone: 'Telefonnummer', district: 'Distrikt', occupation: 'Erhverv', yes: 'Ja', no: 'Nej', dashboard: 'Dashboard', analytics: 'Analyse' },
};

export const languageNames: Record<Language, string> = {
  en: 'English', es: 'Español', fr: 'Français', de: 'Deutsch', it: 'Italiano',
  pt: 'Português', ru: 'Русский', zh: '中文', ja: '日本語', ko: '한국어',
  ar: 'العربية', hi: 'हिन्दी', bn: 'বাংলা', pa: 'ਪੰਜਾਬੀ', te: 'తెలుగు',
  mr: 'मराठी', ta: 'தமிழ்', ur: 'اردو', gu: 'ગુજરાતી', kn: 'ಕನ್ನಡ',
  ml: 'മലയാളം', th: 'ไทย', vi: 'Tiếng Việt', id: 'Bahasa Indonesia',
  tr: 'Türkçe', pl: 'Polski', nl: 'Nederlands', sv: 'Svenska',
  no: 'Norsk', da: 'Dansk',
};

export const languageFlags: Record<Language, string> = {
  en: '🇬🇧', es: '🇪🇸', fr: '🇫🇷', de: '🇩🇪', it: '🇮🇹',
  pt: '🇵🇹', ru: '🇷🇺', zh: '🇨🇳', ja: '🇯🇵', ko: '🇰🇷',
  ar: '🇸🇦', hi: '🇮🇳', bn: '🇧🇩', pa: '🇮🇳', te: '🇮🇳',
  mr: '🇮🇳', ta: '🇮🇳', ur: '🇵🇰', gu: '🇮🇳', kn: '🇮🇳',
  ml: '🇮🇳', th: '🇹🇭', vi: '🇻🇳', id: '🇮🇩',
  tr: '🇹🇷', pl: '🇵🇱', nl: '🇳🇱', sv: '🇸🇪',
  no: '🇳🇴', da: '🇩🇰',
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};